# Практическое задание

In [3]:
import numpy as np

__1.__ Установите, какие произведения матриц $AB$ и $BA$ определены, и найдите размерности полученных матриц:

 а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;

A * B = 4 x 2 * 4 x 2  - произведение не определено<br> 
B * A = 4 x 2 * 4 x 2  - произведение не определено

б)  𝐴  — матрица  2×5 ,  𝐵  — матрица  5×3

A * B = 2x5 * 5x3 = 2x3<br>
B * A = 5x3 * 2x5 -  произведение не определено    

в)  𝐴  — матрица  8×3 ,  𝐵  — матрица  3×8

A * B = 8x3 * 3x8 = 8x8<br>
B * A = 3x8 * 8x3 = 3x3

г)  𝐴  — квадратная матрица  4×4 ,  𝐵  — квадратная матрица  4×4 

A * B = 4x4 * 4x4 = 4x4<br>
B * A = 4x4 * 4x4 = 4x4

__2.__ Найдите сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [11]:
A = np.array([[1,-2], [3,0]])
B = np.array([[4, -1], [0, 5]])
print(f'Сумма матриц A и B = \n{A+B}')
print()
print(f'Произведение матриц A и B = \n{np.dot(A, B)}')

Сумма матриц A и B = 
[[ 5 -3]
 [ 3  5]]

Произведение матриц A и B = 
[[  4 -11]
 [ 12  -3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислите линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [12]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
3*A - 2*B + 4*C

array([[ 11,  -5],
       [  9, -12]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислите $AA^{T}$ и $A^{T}A$.

In [24]:
A = np.array([[4, 1], [5, -2], [2, 3]])
A_t = A.T
print(f'A * A_t = \n{np.dot(A, A_t)}')
print()
print(f'A_t * A = \n{np.dot(A_t, A)}')

A * A_t = 
[[17 18 11]
 [18 29  4]
 [11  4 13]]

A_t * A = 
[[45  0]
 [ 0 14]]


__5*.__ Напишите на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [68]:
def matrix_multuply(A, B):
    '''
    Умножение матрицы А на матрицу B
    '''
    if A.shape[0] == B.shape[1]:
        M = [[0] * A.shape[0] for _ in range(A.shape[0])]
       
        for i in range(A.shape[0]):
            for j in range(A.shape[0]):
                el = 0
                for r in range(A.shape[1]):
                    el += A[i][r] * B[r][j]
                M[i][j] = el
        for row in M:
            print(*row)
        print()    
    else:
        return 'Умножение матриц невозможно'

A = np.array([[1,-2], [3,0]])
B = np.array([[4, -1], [0, 5]])
C = np.array([[4, 1], [5, -2], [2, 3]])
D = np.array([[1, 2, 3, -4], [5, -7, 1, 2], [0, 1, 0, 1], [2, 1, 2, 3], [-1, 1, -2, 2]])
E = np.array([[1, 2, 3, -4, 5], [5, -7, -2, 1, 2], [1, 0, 1, 0, 1], [-5, 2, 1, 2, 3]])
matrix_multuply(A, B)

matrix_multuply(C, A)

matrix_multuply(C, C.T)

matrix_multuply(C.T, C)
matrix_multuply(D, E)

4 -11
12 -3

17 18 11
18 29 4
11 4 13

45 0
0 14

34 -20 -2 -10 0
-39 63 32 -23 18
0 -5 -1 3 5
-6 3 9 -1 23
-8 -5 -5 9 1

